### ISSUE TITLE
运行example，程序无响应了

### ISSUE THREAD

**Issue by feimenggo** [lixp185/bookfx#1]
![1664529277600](https://user-images.githubusercontent.com/12608693/193237059-2cdf1bbb-5806-4ce3-83c7-c50efaba70f9.jpg)

**Comment by lixp185** [comment]
应该在计算文字高度那里的问题，这块计算还有点问题。有时间我优化下

**Comment by lixp185** [comment]
已经修复了，你可以再试试

**Comment by feimenggo** [comment]
现在可以显示了
